name: Node.js CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: cd node/express-prisma-typescript | npm ci
      - name: Run tests
        run: cd node/express-prisma-typescript | npm test
