name: Node.js CI

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1.4.5
        with:
          working-directory: node/express-prisma-typescript
      - name: Run tests
        run: npm test
        working-directory: node/express-prisma-typescript
